
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Students_and_Teachers_Management extends javax.swing.JFrame {

    /**
     * Creates new form Students_and_Teachers_Management
     */
    
     
            
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Students_and_Teachers_Management() {
        initComponents();
        
                
        conn=javaconnect.connerDb();
        CurrentDate();
    }
    
    
        
    public void CurrentDate() 
    {

        
        Thread clock=new Thread()
        {
            public void run()
            {
                for(;;)
                    
                {
                
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        date_txt.setText(day+"/"+(month+1)+"/"+(year));
        
        
        
        int second=cal.get(Calendar.SECOND); 
        int mint=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        txt_time.setText(hour+":"+(mint)+":"+(second));  
        

                    
                    try {
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Students_and_Teachers_Management.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        
        
        
        clock.start();
        
                
    }
    
        
    public  void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_teacher_management = new javax.swing.JLabel();
        txt_student_management = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_teachers = new javax.swing.JButton();
        txt_students = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        date_txt = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_me = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_Employee = new javax.swing.JButton();
        txt_help = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Information");
        setResizable(false);

        txt_teacher_management.setBackground(java.awt.Color.blue);
        txt_teacher_management.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt_teacher_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Teacher-male-icon.png"))); // NOI18N
        txt_teacher_management.setText("Tearchers");
        txt_teacher_management.setToolTipText("Tearcher Management Option-1");
        txt_teacher_management.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_teacher_managementAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txt_student_management.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        txt_student_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Student-3-icon.png"))); // NOI18N
        txt_student_management.setText("Students");
        txt_student_management.setToolTipText("Srudent Management Option-2");
        txt_student_management.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_student_managementAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Data Management System Dashboard");

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("NB: By Click to choice  one");
        jLabel4.setToolTipText("NB: By Click to choice  one");

        txt_teachers.setBackground(java.awt.Color.blue);
        txt_teachers.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_teachers.setForeground(java.awt.Color.white);
        txt_teachers.setText("Teachers");
        txt_teachers.setToolTipText("Teachers Data Entry Option");
        txt_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachersActionPerformed(evt);
            }
        });

        txt_students.setBackground(java.awt.Color.blue);
        txt_students.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_students.setForeground(java.awt.Color.white);
        txt_students.setText("Students");
        txt_students.setToolTipText("Students Data Entry Option");
        txt_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentsActionPerformed(evt);
            }
        });

        date_txt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        date_txt.setText("Current Date:");

        txt_time.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txt_time.setText("Time:");

        jButton2.setBackground(java.awt.Color.green);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Current date:");
        jButton2.setToolTipText("Current date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.green);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Time:");
        jButton3.setToolTipText("Time");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.green);
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Close");
        jButton4.setToolTipText("Close The Window");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_me.setBackground(new java.awt.Color(255, 255, 255));
        txt_me.setFont(new java.awt.Font("Arial", 0, 1)); // NOI18N
        txt_me.setForeground(java.awt.Color.white);
        txt_me.setText("About me");
        txt_me.setToolTipText("About me");
        txt_me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_meActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Person-Male-Light-icon.png"))); // NOI18N
        jLabel2.setText("Employees");
        jLabel2.setToolTipText("Employee Management Option-3");

        txt_Employee.setBackground(java.awt.Color.blue);
        txt_Employee.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_Employee.setForeground(java.awt.Color.white);
        txt_Employee.setText("Employees");
        txt_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeActionPerformed(evt);
            }
        });

        txt_help.setBackground(java.awt.Color.green);
        txt_help.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_help.setForeground(java.awt.Color.white);
        txt_help.setText("Help");
        txt_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(txt_teachers, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(txt_students, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(txt_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(txt_teacher_management, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_student_management, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date_txt)
                                .addGap(39, 39, 39)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txt_help, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addComponent(txt_me, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(342, 342, 342))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_me, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_help)
                        .addComponent(txt_time)
                        .addComponent(jButton3)
                        .addComponent(date_txt)
                        .addComponent(jButton2)
                        .addComponent(jButton4)))
                .addGap(115, 115, 115)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_teacher_management, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_student_management, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_teachers, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(314, 314, 314)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(704, 704, 704))
        );

        txt_student_management.getAccessibleContext().setAccessibleDescription("Student Management Option-2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_teacher_managementAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_teacher_managementAncestorAdded
        // TODO add your handling code here:

        
    }//GEN-LAST:event_txt_teacher_managementAncestorAdded

    private void txt_student_managementAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_student_managementAncestorAdded
        // TODO add your handling code here:

        
        
        
    }//GEN-LAST:event_txt_student_managementAncestorAdded

    private void txt_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachersActionPerformed
        // TODO add your handling code here:
        

                Teachers_Information_System t = new Teachers_Information_System();
                t.setVisible(true);
                close();
    }//GEN-LAST:event_txt_teachersActionPerformed

    private void txt_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentsActionPerformed
        // TODO add your handling code here:
        
                 Students_Infromation_System s = new Students_Infromation_System();
                 s.setVisible(true);
                 close();
    }//GEN-LAST:event_txt_studentsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_meActionPerformed
        // TODO add your handling code here:
        
                 My_Profile s = new My_Profile();
                 s.setVisible(true);
                 
        
    }//GEN-LAST:event_txt_meActionPerformed

    private void txt_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeActionPerformed
        // TODO add your handling code here:
        
                
                 Employees_Infromation_System s = new Employees_Infromation_System();
                 s.setVisible(true);
                 close();
        
    }//GEN-LAST:event_txt_EmployeeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_helpActionPerformed
        // TODO add your handling code here:
        
                 Help s = new Help();
                 s.setVisible(true);
                 close();
    }//GEN-LAST:event_txt_helpActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton txt_Employee;
    private javax.swing.JButton txt_help;
    private javax.swing.JButton txt_me;
    private javax.swing.JLabel txt_student_management;
    private javax.swing.JButton txt_students;
    private javax.swing.JLabel txt_teacher_management;
    private javax.swing.JButton txt_teachers;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
